// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3LmWAe0L_NqYmO-EtZElt9-nca2w4Ts',
    appId: '1:103768268341:web:eaca6a47979e59ca4d1b7c',
    messagingSenderId: '103768268341',
    projectId: 'chat-bbbb9',
    authDomain: 'chat-bbbb9.firebaseapp.com',
    storageBucket: 'chat-bbbb9.firebasestorage.app',
    measurementId: 'G-7WXT5TXLXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8K0RFRVlFp8lse87Y-Qfe2EwhNPuywZQ',
    appId: '1:103768268341:android:394e570c984130a44d1b7c',
    messagingSenderId: '103768268341',
    projectId: 'chat-bbbb9',
    storageBucket: 'chat-bbbb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcc_oXlqrXAtTRjfvxxm141fyMbWQtzAk',
    appId: '1:103768268341:ios:7d1b122785c3d63a4d1b7c',
    messagingSenderId: '103768268341',
    projectId: 'chat-bbbb9',
    storageBucket: 'chat-bbbb9.firebasestorage.app',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
